### PR TITLE
4max pro 2 dgus fixes

### PR DESCRIPTION
**Pull request by etet100**
I prepared some changes to improve support for my 4MAX PRO 2.0 printer with Anycubic 0.0.2 display.

### CODE REVIEW

**Comment by Truggy** [comment]
Knutwurst - Will these be merged? Do you need a tester?

Thanks

**Comment by etet100** [comment]
I'm sorry. I have deciced not to waste my time on trying work around problems with this crappy display. Now i'm working on new firmware (for anycubic tft v0.0.2) which will be based on standard gcode protocol. This will allow me to use unmodified marlin or slightly modified klipper.

**Comment by Truggy** [comment]
Ok. Keep us posted. Thanks

**Comment by knutwurst** [comment]
@etet100 that's a shame, but understandable. Would you mind if I made some of the code changes (on your behalf) anyway? I don't want it to appear like I'm "stealing" from you. But you had good ideas that I would like to adopt :)

**Comment by etet100** [comment]
Actually i wonder why there is so much logic in tft display class. Have you tried to use ExtUI? For example

```
ExtUI::pausePrint();
ExtUI::pausePrint();
ExtUI::resumePrint();
and events:
void onMediaInserted() {}
void onMediaRemoved() {}
void onPrintTimerStarted() {}
void onPrintTimerPaused() {}
void onPrintTimerStopped() {}
void onFilamentRunout(const extruder_t extruder) {}
void onUserConfirmRequired(const char * const msg) {
void onStatusChanged(const char * const msg) {}
void onHomingStart() {}
void onHomingComplete() {}
void onPrintFinished() 
```

Delegating this type of basic logic to external module is a simple way to disaster.

**Comment by knutwurst** [comment]
Quite simply because at the time when I developed this firmware, there was no ExtUI for the Anycubic displays! Marlin 1.1.9 and later 2.0.5 did not have any support for these features yet and since I have a lot of custom code in my display class, it was easier to continue using this code when updating to Marlin 2.0.9.

As far as I know, only rudimentary features of the Anycubic display are controlled via ExtUI. And so far there is no support for the Anycubic 0.0.2 display either.

Sure - I *could* convert my entire code to ExtUI and push that directly into the Marlin sources, but this is a project that I do in my spare time. Nobody pays me for such an unspeakable task of basically rewriting everything.

You are very welcome to do that! But I just don't have the time or inclination to do it.

ExtUI makes sense when it comes to keeping the firmware as generic as possible. But I'm only developing alternative firmware for Anycubic printers. That's why I'm not going to start recreating menus and sub-menus in ExtUI just to make the code nicer.

If you put on pure Marlin and use ExtUI, you will quickly see what works well and what unfortunately doesn't.

**Comment by etet100** [comment]
Thanks. It makes sense.

I have almost finished porting BigTreeTech firmware to Anycubic display. It should work more reliably.
image

**Pull request closed without merging**
