### PR TITLE
Using the BLTouch as Z-Endstop

### PR DESCRIPTION
**Pull request by this-snow**
Changes to use the BlTouch as an End Z-Stop. Way more structured on GitHub than in the Facebook Group, for anyone who also wants to implement it.
I haven't changed anything in the base either, that should be possible with a simple define.

// German
Ich dachte es ist einfacher die notwendigen Änderungen für den BlTouch Z Endstop hier festzuhalten, in der Facebook Gruppe geht das verloren. Durch den define sollten auch weniger versierte Personen das hinbekommen.
Kannst es auch einfach als pr hier drinlassen, dann hat man die Änderungen ja auch übersichtlich gezeigt.

### Requirements

* **VSCode** with Platform.io if someone wants to build the Version with BLTouch Z Endstop.
* (Original) **BLTouch**
* Connect BLTouch cables **(white + black)** to the original endstop cable **(right side)**
* **Z-Endstops dismantled**

### CODE REVIEW

**Comment by knutwurst** [comment]
That looks very promising! Thanks a lot for this! My idea now was to move the pins on the board so that you don't have to switch off the Z-Endstops if you flash this firmware and have installed the BLTouch beforehand according to the instructions.

Theoretically, it should work, but unfortunately I hardly have time to test it myself with my printer because I won't be home for a few weeks.

Is it okay if I leave your pull request open for now? But I see your development and I really like the implementation!

**Comment by this-snow** [comment]
That is perfectly fine. I just did it for myself and thought it would be helpful to post it here in case anyone wants to try it.
If you have an idea how it could be done better without taking too much time to explain, you could describe it briefly.
Then I could do it and test it on myself. I have a lot of free time at the moment.

**Review by this-snow — COMMENTED** [review]
Does not work this way lol

**Comment by will-stevenson** [comment]
> That is perfectly fine. I just did it for myself and thought it would be helpful to post it here in case anyone wants to try it.
> If you have an idea how it could be done better without taking too much time to explain, you could describe it briefly.
> Then I could do it and test it on myself. I have a lot of free time at the moment.

You've defined the z_min_pin to use the servo pin, wouldn't you want this defined to use the original pin used by the BLTouch - Pin 2?

**Comment by will-stevenson** [comment]
> > That is perfectly fine. I just did it for myself and thought it would be helpful to post it here in case anyone wants to try it.
> > If you have an idea how it could be done better without taking too much time to explain, you could describe it briefly.
> > Then I could do it and test it on myself. I have a lot of free time at the moment.
> 
> You've defined the z_min_pin to use the servo pin, wouldn't you want this defined to use the original pin used by the BLTouch - Pin 2?

FYI, I have tested this myself, and I have it working now using the BLTouch signal pins rather than the z-min (right z-stop).

if you like, you can check out my fork and see how i've integrated all of the bl-touch z-endstop / z-stepper alignment. I've modified my printer now with fixed aluminium spacers instead of springs, and added a 5th screw to the middle of the plate to make my printer levelling fully automated.

**Comment by timoth31590** [comment]
I'm trying it, but the hotend goes into the bed. BL touch white wire is one right z endstop green and black on black. The BLtouch triggers but the Z axis keeps going.

**Comment by timoth31590** [comment]
Should the home in the slicer be in the center with this mod? Because by home all on the display it goes to the center

**Comment by Pkahl** [comment]
Danke ich hatte Problemme mit anycubic i3 mega s mit BLTouch wegen der Configuration.h Datei ich habe ständig einen Fehler in der konsole bekommen für den BLToch aber deinen Configuration.h Datei hat bei mir prima funktioniert Danke

**Comment by jbrandek** [comment]
> > > That is perfectly fine. I just did it for myself and thought it would be helpful to post it here in case anyone wants to try it.
> > > If you have an idea how it could be done better without taking too much time to explain, you could describe it briefly.
> > > Then I could do it and test it on myself. I have a lot of free time at the moment.
> > 
> > 
> > You've defined the z_min_pin to use the servo pin, wouldn't you want this defined to use the original pin used by the BLTouch - Pin 2?
> 
> FYI, I have tested this myself, and I have it working now using the BLTouch signal pins rather than the z-min (right z-stop).
> 
> if you like, you can check out my fork and see how i've integrated all of the bl-touch z-endstop / z-stepper alignment. I've modified my printer now with fixed aluminium spacers instead of springs, and added a 5th screw to the middle of the plate to make my printer levelling fully automated.

Can you post some pictures of the changes you made?

**Comment by t-poeschl** [comment]
Someone has an current Version, where the BL Touch acting as Z-Endstop?

**Comment by knutwurst** [comment]
Hi @t-poeschl ,
no, there is no preconfigured version which has this feature, because the dual z axis leveling is slow af and you need to adjust the bed every single time before printing. This is why I never included this feature. Also the limit switches are indeed more accurate compared to the bltouch probe.

But, if you like, take a look at this: https://github.com/knutwurst/Marlin-2-0-x-Anycubic-i3-MEGA-S/pull/61/files#diff-bb298d18dac4268225a7a53a5ad24844472530bdc63f6a98a2ba8d8158b75080

As you can see, it's not much at all. All you need to is copy&paste the small changes in the configuration.h which work for your printer. Also you need to set the probe pin accordingly in the pins_ramps.h. That's all. 

A manual how to compile the firmware by yourself can be found in the wiki.

Best,
Olli

**Pull request closed without merging**
