### PR TITLE
update code base to Marlin 2.0.9.2 

### PR DESCRIPTION
**Pull request by stklcode**
### Description

This PR updates the upstream sources to [Marlin 2.0.9.2](https://github.com/MarlinFirmware/Marlin/tree/2.0.9.2)

#### ExtUI vs custom implementation

ExtUI is _not_ used, so the custom implementation including special menu are still in place.

Just updated some renamed functions and macros to make it compatible.

#### Changed files

All changes I could make out in the current state are marked with
```cpp
// PATCH START: Knutwurst
...
// PATCH END: Knutwurst
```
or inline
```cpp
... // PATCH Knutwurst`.
```

The backports of e.g. _MeatPack_ support will be replaced by the unmodified upstream sources.

#### Tested
The firmware builds for some random targets including "CHIRON".

I've tested the "MEGA_P_BLT_10" target on my printer, including special menu and Autoleveling. Works so far.

### Benefits

The updates introduces new features and bugfixes in Marlin. It also brings this project closer to upstream for future development.

### Configurations

The configuration files have been updated and hopefully all customization remain functional. No additional files needed.

### Related Issues

No currently open issue.

### CODE REVIEW

**Comment by stklcode** [comment]
Rebased onto master branch and migrated 4Max config, too.

**Comment by knutwurst** [comment]
Whew! I didn't expect that. You did what I never wanted to do :D
Great! However, it is very difficult to trace each change individually now. I will merge the pull request and then build through all the variants for a new beta version.

Since I don't have a QA team, the product has to mature with the customer :D

THANKS ALOT! 🥇

**Comment by stklcode** [comment]
Good to hear that my work was not lost.

I know a lot of code was moved, but my hope is that future Marlin updates will be smoother once the code is close to it.

As always, I probably test every update on my Mega P with BLT. All I can tell about other printers is that the PIO process completes...

**Comment by knutwurst** [comment]
@stklcode ... great... I couldn't add a custom message to my sponsoring :D 

It has now become a bit quiet around the subject (among other things, because I still have a real job). Maybe we want to keep in touch? If you like, you can contact me via Discord (Knutwurst#7588) or [Thingiverse](https://www.thingiverse.com/knutwurst/designs).

Best,
Olli

**Pull request merged**
