### PR TITLE
Backport meatpack feature from upstream

### LINKED ISSUE #97: [FR] MEATPACK enabled?
Is the MEATPACK pre-compiler option set in the pre-compiled binaries?

More info here:

https://github.com/scottmudge/OctoPrint-MeatPack/

### PR DESCRIPTION
**Pull request by ashleysommer**
Fixes #97 
Tested on MEGA-S (Old TFT, No BLT).

### CODE REVIEW

**Comment by ashleysommer** [comment]
image

**Comment by ashleysommer** [comment]
It might be placebo, but my during my tests, the printer felt more responsive, streaming from Octoprint on my old RPI3. Exactly what enabling Meatpack is supposed to do, and exactly the problem I was hoping to solve.

**Comment by knutwurst** [comment]
Wow Ashley! Great Job! I'll take a look, merge and create a new prerelease-version!

**Comment by MrBill1234** [comment]
Fantastic - when do you think this will make it into a release?

Up until now i've been using the David Ramiro 1.19 firmware.  Would there be any major differences I would notice if upgrading to this?

**Comment by knutwurst** [comment]
Bildschirmfoto 2021-08-20 um 10 27 00
All tests were successful. Building a prerelease version now.

**Pull request merged**
